- Gemfile
- Gemfile.lock
This PR upgrade dor-services to 5.8.2 to fix the `.save` problem with the Solr 6 upgrade. It was previously running on 5.4.2.
> bundle update dor-services to 5.8.2

- Gemfile
- Gemfile.lock
@cbeer Interestingly enough, it didn't send a honeybadger notification :(
See https://github.com/drbrain/net-http-persistent/issues/80 for note on incompatibility
```
ERROR [2017-07-19 11:46:35] (6403)  :: Cannot set druid:hs625cr1878 to status='error'
wrong number of arguments (given 1, expected 0)
/opt/app/lyberadmin/gis-robot-suite/shared/bundle/ruby/2.3.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505
:in `initialize'
/opt/app/lyberadmin/gis-robot-suite/shared/bundle/ruby/2.3.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http_persistent.r
b:22:in `new'
/opt/app/lyberadmin/gis-robot-suite/shared/bundle/ruby/2.3.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http_persistent.r
b:22:in `net_http_connection'
/opt/app/lyberadmin/gis-robot-suite/shared/bundle/ruby/2.3.0/gems/far …
```
> rollback net-http-persistent due to incompatibility with faraday

- lib/xslt/mods2geoblacklight.xsl
This PR changes the XSLT from MODS to GeoBlacklight to work with the GeoBlacklight v1.0 schema (basically adds `geoblacklight_version` and drops other fields).
@mejackreed @kimdurante
> upgrade to GeoBlacklight v1.0 schema

- Gemfile
- Gemfile.lock
- robots/gisDiscovery/export-opengeometadata.rb
- robots/gisDiscovery/finish-gis-discovery-workflow.rb
- robots/gisDiscovery/generate-geoblacklight.rb
- robots/gisDiscovery/load-geoblacklight.rb
This PR fixes #121, and fixes #123 by:
- `generate-geoblacklight` reorganized to generate a JSON version of GeoBlacklight record
- use `GeoCombine::Geoblacklight.enhance_metadata` on that JSON version
- `load-geoblacklight` use the `.json` version rather than the `.xml` to load into Solr
- `export-opengeometadata` just copies the `.json` file (XML conversion code moved to generate-geoblacklight)
- remove dead code in the final noop step robot
Tested in -dev environment.
> Use geocombine for enhancement

- lib/gis-robot-suite/utils.rb
- robots/gisAssembly/approve-data.rb
- robots/gisAssembly/approve-metadata.rb
- robots/gisAssembly/normalize-data.rb
- robots/gisDelivery/load-geoserver.rb
- robots/gisDelivery/load-geowebcache.rb
The purpose of NotImplementedError from rubydocs is:
> NotImplementedError is raised when a feature is not implemented on the current platform. For  example, methods depending on the fsync or fork system calls may raise this exception if the underlying operating system or Ruby runtime does not support them.
> Don't abuse NotImplementedError

- config/deploy.rb
To further unify deployments for robot suites with a single resque-pool
A PR to DevOpsDocs is at https://github.com/sul-dlss/DevOpsDocs/pull/335
> Replace robot full_restart with hot_swap

- config/deploy.rb
- config/settings.yml
gis-robots were busted in production  (and in stage, no doubt) - this fixed them. 
n/a
> Fix deploy

- robots/gisDiscovery/generate-geoblacklight.rb
This is no longer part of Dor::Services.config.
See https://github.com/sul-dlss/gis-robot-suite/pull/236
Fixes #252
n/a
> Use the settings for the stacks url

- bin/run_robot
It's deprecated because it's a lot more indirection than is required
> Avoid LyberCore::Robot.step_to_classname

- robots/gisAssembly/load-geo-metadata.rb
- spec/unit/gisAssembly/load_geo_metadata_spec.rb
Connects to sul-dlss/dor-services-app#679
To use the new endpoint, in advancing an SDR evolution goal.
No.
Yes. DSA endpoint has been tested in stage.
> [HOLD] Use new DSA endpoint for administrative tags

- robots/gisAssembly/load-geo-metadata.rb
- spec/unit/gisAssembly/load_geo_metadata_spec.rb
Fixes #266
The test setup hid the underlying error.
no
Yes, it should restore the connection to DSA.
> Fix load-geo-metadata robot in gisAssemblyWF

- .gitignore
- README.md
- config/boot.rb
- config/environments/test.rb
- config/settings/test.yml
- spec/spec_helper.rb
Connects to #186
Connects to #268
Required some setup of the test environment, which should not interfere with deployments (which are in production and staging envs).
Because test coverage is currently showing at 0% but it's slightly higher than zero.
Yes, tweaked the badges a bit.
No, should not.
> Restore test coverage

- config/deploy.rb
This allows us to `SKIP_BUNDLE_AUDIT=true cap deploy` in order to deploy with some of the older dependencies that are not passing audit. Discussion of how to handle those dependencies is ongoing.
Manually deployed to stage
> Enable bundler2 style config

- config/deploy.rb
we use the capistrano/rvm gem now
no
n
> Remove settings for the outdated rvm/capistrano plugin

- config/deploy.rb
They weren't getting linked.
Deployed on prod and tested manually
n/a
> Link the geoserver files from shared configs

- Gemfile
- Gemfile.lock
NOTE:  after this, rebase #315 and merge, THEN deploy.
Closes #313
To fix production problem.  HB alert:  https://app.honeybadger.io/projects/52899/faults/64814119
It wasn't.  We appear to have no test code that tests this.  We should but I'm not going to puzzle it out right now.  If a reviewer wants to add a commit that would be grand.
Gemfile updated.
> add druid-tools to Gemfile explicitly

- config/boot.rb
- config/environments/example.rb
- config/environments/production.rb
- config/environments/staging.rb
Fixes https://github.com/sul-dlss/gis-robot-suite/issues/316
Test suite
`config/environments/*.rb` had the path removed because we can just set it once in config/boot.rb
> Use the correct path to the rgeoserver_config

- config/settings.yml
- lib/gis_robot_suite.rb
- lib/robots/dor_repo/gis_assembly/extract_boundingbox.rb
- lib/robots/dor_repo/gis_assembly/generate_mods.rb
- lib/robots/dor_repo/gis_assembly/normalize_data.rb
With the centos 7 upgrade we can't expect the robots to have the gdal commands available on the path. This allows us to specify the location of this library.
Deployed onto kurma-robots1-stage and tested.
Needed shared configs here: https://github.com/sul-dlss/shared_configs/pull/1416 and prod will need that when upgraded to centos7
> Make the gdal path configurable

- config/environments/example.rb
- config/environments/production.rb
- config/environments/staging.rb
Because dor-services gem was removed in https://github.com/sul-dlss/gis-robot-suite/commit/539a778694faf8e7aedb8cedd46b0e4ecac1e34f
test suite
n/a
> Remove Dor::Config

- config/deploy.rb
Removing legacy linked files, previous work moved this to a more "shared configs" based config #333
> Remove legacy rgeoserver linked configs

- Gemfile
- Gemfile.lock
CVE on addressable gem was blocking deploy.
Unit
> Update dependencies due to CVE with addressable gem.

- config/deploy/qa.rb
robots resque-pool and robot console weren't usable on the QA instance of gis-robot-suite
we'll deploy to QA to test
just the QA deploy config
> QA should see itself as production

- config/settings.yml
No longer needed since gisDiscoveryWF was removed. 02185f4#diff-ed29dc27cd08d28e4f9902ec125190bd7e8ec2548d1601b4c899a0779b06ac5b
> Remove unused config variables

- config/deploy/qa.rb
The new server name is kurma-robots-qa-01
New kurma QA db and robot servers were built, with new server names (kurma-db-qa-01,kurma-db-qa-02,kurma-robots-qa-01)
cap deploy
DevOpsDocs PR put in to include QA servers
> Update QA deploy server

- config/deploy/qa.rb
Hot swapping resque pool hangs in QA due to the OS.  Apply same fix as was needed for preservation catalog: https://github.com/sul-dlss/preservation_catalog/blob/main/config/deploy/prod.rb#L9-10
Testing command on QA
> fix issue with hanging resque pool on qa

- config/deploy/stage.rb
the old hostname no longer resolves, now that the box has been rebuilt on ubuntu and given a hostname that follows our current conventions.
i was able to `bundle exec cap stage ssh` successfully, whereas i'd get a connection error before this fix.
> update hostname for new stage box

- config/deploy/stage.rb
deployment hung on resque-pool hotswap.  this change fixed that problem for other ubuntu deployments, e.g.:
https://github.com/sul-dlss/preservation_catalog/blob/4f23bdf56a391fd59c05e86389d4c13cb77a9967/config/deploy/prod.rb#L9-L10
> cap terminal setting for ubuntu so that terminal session doesn't mysteriously hang when running resque-pool hotswap, see also e.g. pres cat prod

- lib/robots/dor_repo/gis_assembly/generate_content_metadata.rb
Fixes #521
A hash that used to live in assembly-objectfile was removed, but gis-robot-suite needs it. So copy it in.
CI
> Copy file attrs hash from removed dependency

- .rubocop.yml
- README.md
- lib/robots/dor_repo/gis_assembly/generate_geo_metadata.rb
- lib/robots/dor_repo/gis_assembly/generate_mods.rb
- lib/robots/dor_repo/gis_assembly/load_geo_metadata.rb
- spec/robots/dor_repo/gis_assembly/generate_mods_spec.rb
Removed references to "datastream" which are no longer relevant, in a post Fedora 3 world.
**Ignore coverage drop** - look at the files;  no code was really changed, just comments and a method name.
> remove references to Fedora and Datastream

- config/deploy/prod.rb
This simply points at the new server URL for production deployment.
> Update production url to new path

- config/deploy.rb
- config/deploy/qa.rb
- config/deploy/stage.rb
> cap deploy sets :pty to true for all deployed environments

- .rubocop.yml
- lib/gis_robot_suite.rb
- lib/robots/dor_repo/gis_assembly/extract_boundingbox.rb
- lib/robots/dor_repo/gis_assembly/normalize_data.rb
- spec/robots/dor_repo/gis_assembly/load_geo_metadata_spec.rb
Enable new cops, autocorrect errors.
> Enable new cops and fix linting errors

- Rakefile
- config/deploy.rb
- config/settings/test.yml
noticed that default `bundle exec rake` ran into errors around the things cleaned up in this commit (error trying to create Resque related Rake tasks since switch to Sidekiq, error trying to load `VERSION` file that was removed for lack of usefulness)
`bundle exec rake` on dev laptop, CI
> Unbreak rake etc

- lib/gis_robot_suite.rb
- lib/robots/dor_repo/gis_delivery/load_geoserver.rb
- lib/robots/dor_repo/gis_delivery/reset_geowebcache.rb
- spec/robots/dor_repo/gis_delivery/load_geoserver_spec.rb
- spec/robots/dor_repo/gis_delivery/reset_geowebcache_spec.rb
- spec/spec_helper.rb
- spec/unit/utils_spec.rb
The robot already retrieves cocina object.
Unit
> Avoid dupe retrieval when checking rights.

- README.md
I discovered that we couldn't test the robots that transform XML in CI without installing these dependencies, so I decided to document them.
The CI workflow now installs them and runs successfully as of #678
> Add info about XML dependencies to README

- lib/robots/dor_repo/gis_assembly/extract_iso19139.rb
- spec/robots/dor_repo/gis_assembly/extract_iso19139_spec.rb
- Only generate iso19110 if we have a shapefile
- Make sure we generate fgdc for all data types
- Cleaner method for getting the project directory
- General code cleanup and documentation
Fixes #104
Fixes #583
> Refactor extract-iso19139 robot

- lib/robots/dor_repo/gis_assembly/extract_iso19139.rb
Partially addresses #665 to remove geoMetadata check from workflow steps. We should follow the rest of the existing logic to generate the metadata in this step. 
Unit.
> Remove geoMetadata check from extract_iso19139

- lib/gis_robot_suite.rb
- lib/robots/dor_repo/gis_assembly/normalize_data.rb
- spec/unit/utils_spec.rb
To use cocina instead of MODS.
Unit
> [HOLD] Refactor determine_projection to use cocina.

- lib/robots/dor_repo/gis_assembly/finish_gis_assembly_workflow.rb
- lib/robots/dor_repo/gis_assembly/finish_metadata.rb
So that descMetadata.xml can be removed.
> Remove checks for descMetadata.xml

- lib/robots/dor_repo/gis_assembly/generate_content_metadata.rb
So the descMetadata.xml can be removed.
Note that this PR does the least bit possible, as there is a separate ticket for refactoring this robot more broadly.
It isn't.
> Remove dependence on descMetadata.xml from Generate Content Metadata robot

- lib/robots/dor_repo/gis_delivery/load_raster.rb
So that we can get rid of descMetadata.xml.
It isn't.
> Refactor load vector robot to not use cocina

- lib/robots/dor_repo/gis_delivery/load_raster.rb
So that no longer need descMetadata.xml
It isn't.
> Refactor load raster robot to not use descMetadata.xml

- lib/robots/dor_repo/gis_assembly/extract_iso19139.rb
Fixes error with `extract_iso19139` step where `xsltproc` was not finding the .xsl file. Restored the previous absolute path for the transforms files. 
Integration test and added logging. 
BEFORE: was looking for `.xsl` in:
`/gis_workflow_data/stage/sr240kw9105/temp/config/ArcGIS/Transforms/ArcGIS2ISO19139.xsl`
AFTER:
`generating /gis_workflow_data/stage/wg313th2970/temp/AirMonitoringStations-iso19139.xml using /opt/app/lyberadmin/gis-robot-suite/releases/20240122155528/config/ArcGIS/Transforms/ArcGIS2ISO19139.xsl`
> Change basepath for transforms dir

- lib/robots/dor_repo/gis_assembly/normalize_data.rb
- spec/robots/dor_repo/gis_assembly/normalize_data_spec.rb
To stop using descMetadata.xml
Unit
> Refactor Normalize Data robot to use cocina.

- lib/robots/dor_repo/gis_assembly/extract_boundingbox.rb
- spec/robots/dor_repo/gis_assembly/extract_boundingbox_spec.rb
closes #601
Dir.chdir was causing intermittent `Errno::ENOENT: No such file or directory - getcwd` errors.
Unit
> Remove use of Dir.chdir in Extract Boundingbox robot.

- README.md
- bin/run_delivery
- lib/robots/dor_repo/gis_delivery/start_accession_workflow.rb
Resolves #715 to kick off accessionWF after gisDeliveryWF. Goes with workflow-server PR: https://github.com/sul-dlss/workflow-server-rails/pull/711
Tested with integration test on a branch. (See PR )
> Add step to kick off accessionWF

- lib/gis_robot_suite/gazetteer.rb
- lib/robots/dor_repo/gis_assembly/assign_placenames.rb
- spec/gis_robot_suite/gazetteer_spec.rb
- spec/robots/dor_repo/gis_assembly/assign_placenames_spec.rb
closes #705
Get rid of MODS.
Unit
> Change Assign Placenames robot to update cocina directly.

- lib/robots/dor_repo/gis_assembly/normalize_data.rb
- spec/robots/dor_repo/gis_assembly/normalize_data_spec.rb
Reprojection is supposed to occur not NOT EPSG 4326.
Unit
> Fix projection logic for Normalize Data robot.

- lib/robots/dor_repo/gis_assembly/normalize_data.rb
- spec/robots/dor_repo/gis_assembly/normalize_data_spec.rb
We want to add an alpha channel to GeoTIFF files so they display well in GeoServer. Note, an alpha layer is always added (to single and 3 band GeoTIFF files) since gdalwarp doesn't add a new alpha band if one is already present.
Fixes #570
> Add an alpha layer to GeoTIFF raster data

- spec/robots/dor_repo/gis_assembly/package_data_spec.rb
Extracted from #742 but without the renaming of the ZIP file - so a new spec for the package-data robot that verify it works.
New spec
> add spec for package_data robot

- Gemfile
- Gemfile.lock
- bin/run_robot
The run_robot script is currently broken and needs to be updated.  This has it match what is in common_accessioning.
BUT: the run_robot will not actually run a step, unless it is in the `queued` state (this is true of common_accessioning too) because of a change that happened in `lyber-core` about 1 year ago here: https://github.com/sul-dlss/lyber-core/commit/628a2c37e2c2178423e082dbe60a5453eb959b9d  where we removed the ability to skip the `queued` state check.
~~This PR would add the ability back into `lyber-core`: https://github.com/sul-dlss/lyber-core/pull/152~~
~~If accepted, we would need to cut a new release and then use it here.~~ DONE
On stage
> Fix run_robot script

- lib/gis_robot_suite.rb
- lib/robots/dor_repo/gis_delivery/load_geoserver.rb
- spec/robots/dor_repo/gis_delivery/load_geoserver_spec.rb
- spec/unit/utils_spec.rb
Resolves #565. Sends a PUT request when the coverage is being updated rather than trying to create it again. Also includes some refactoring.
Adding specs and ran integration test. @kimdurante ran a test of re-accessioning and the error no longer occurred.
> load-geoserver updates raster coverage

- Gemfile
- Gemfile.lock
There was/is no need to pin the config gem
integration test for gis robots
> config gem unpinned

- lib/robots/dor_repo/gis_delivery/reload_geoserver.rb
Fixes #774 - raise error on failed API call (should put step in error state)
> raise error if geoserver call fails

- lib/robots/dor_repo/gis_delivery/reload_geoserver.rb
Fixes bug where `Not Found` error was raised by geoserver on `/reload` request.
Integration and on `bin/console`.
> Update geoserver reload path

- lib/robots/dor_repo/gis_assembly/generate_content_metadata.rb
- spec/robots/dor_repo/gis_assembly/generate_content_metadata_spec.rb
Fixes #776 - remove normalized Data zip file from structural
Note: it will still be created in an earlier step, but since it isn't in structural, it will be ignored by shelve/publish and will be cleaned up later.
There is follow on work ticketed elsewhere that may stop this normalized data zip from even being created.  This work should be unaffected by later changes.
~~HOLD for test on stage~~
If merged, go immediately to https://github.com/sul-dlss/infrastructure-integration-test/pull/686
Updated specs
> do not add data_EPSG_4326.zip to structural

- Gemfile
- README.md
- bin/run_assembly
- lib/robots/dor_repo/gis_assembly/generate_structural.rb
- spec/robots/dor_repo/gis_assembly/generate_structural_spec.rb
Fixes #784 - rename `generate-content-metadata` to `generate-structural`
Must go with https://github.com/sul-dlss/workflow-server-rails/pull/720
HOLD for coordination with workflow-server-rails deploy
CI
> Rename generate-content-metadata robot

- Gemfile
- Gemfile.lock
- config/settings.yml
- lib/robots/dor_repo/base.rb
- lib/robots/dor_repo/gis_delivery/reload_geoserver.rb
- spec/robots/dor_repo/gis_delivery/reload_geoserver_spec.rb
fixes #786
- you can see the new test case for the desired retry behavior [failing in CI for the 2nd commit](https://app.circleci.com/pipelines/github/sul-dlss/gis-robot-suite/1506/workflows/88eeda4f-6421-411a-9773-efb2ee05123c/jobs/2404?invite=true#step-108-36792_134), but [passing in CI when the retry behavior is added in the 3rd commit](https://app.circleci.com/pipelines/github/sul-dlss/gis-robot-suite/1507/workflows/9c2a4669-5e19-47bf-85ab-4e1e1f61fc97/jobs/2406?invite=true#step-108-41175_23).
- commit 1 just adds tests for the `ReloadGeoserver` happy path, since that class seemed uncovered.
> ReloadGeoserver: add specs, retry connection failures

- lib/gis_robot_suite/arcgis_metadata_transformer.rb
See https://app.honeybadger.io/projects/52899/faults/104878369 triggered by reseting https://argo-stage.stanford.edu/view/druid:bd882yq4680 ... when we hit a problem transforming metadata, we get the wrong exception.  This fixes the raise so it won't break (`format` is undefined and it gets confused with the ruby `format`, `output` is a string for the file we are trying to transform to)
> fix exception not raised correctly

- lib/robots/dor_repo/gis_assembly/extract_boundingbox.rb
- lib/robots/dor_repo/gis_assembly/generate_mods.rb
- spec/robots/dor_repo/gis_assembly/extract_boundingbox_spec.rb
- spec/robots/dor_repo/gis_assembly/generate_mods_spec.rb
closes #738
Reading JSON is better than parsing text output.
Unit
> Changes ogrinfo to use json output.

- lib/robots/dor_repo/gis_delivery/load_raster.rb
- spec/robots/dor_repo/gis_delivery/load_raster_spec.rb
Fixes #758 - adds a spec for load raster
~~Blocked by https://github.com/sul-dlss/gis-robot-suite/pull/818 ... we need that first, then just take the best parts of the load_raster_spec
the changes in this PR to the load_raster robot can likely all be tossed~~
CI
> Add spec for load_raster

- spec/robots/dor_repo/gis_delivery/load_vector_spec.rb
Fixes #759 - add a new spec for load-vector 
~~Blocked by #818 ... we need that first, then just take the best parts of the load_vector_spec
the changes in this PR to the load_vector robot can likely all be tossed~~
CI
> add spec for load_vector

- lib/robots/dor_repo/gis_assembly/generate_structural.rb
- spec/robots/dor_repo/gis_assembly/generate_structural_spec.rb
Fixes #840 - raise an exception if the preview.jpg file is missing, so we can get a better error message.
Presumes that each GIS object must have a preview.jpg (true?)
new test
> show appropriate error when preview.jpg missing

- lib/gis_robot_suite.rb
Small PR to make the `vector?` method follow the pattern of the `raster?` method just below it.
> Make sure vector? and raster? use the same pattern.

- lib/gis_robot_suite/descriptive_metadata_builder.rb
- spec/fixtures/bh432xr2264-iso19139.xml
Adjust descriptive mapping to not require a publisher, and require a publication date. Also fix a bug where if there were multiple dates, the text of all of them concatenated was parsed. Instead, use the date with a type of "publication". 
Unit and integration.
> Make publication date required, but not publisher

- config/sidekiq.yml
- lib/gis_robot_suite/vector_normalizer.rb
- lib/robots/dor_repo/gis_delivery/load_raster.rb
- lib/robots/dor_repo/gis_delivery/load_vector.rb
- spec/gis_robot_suite/vector_normalizer_spec.rb
- spec/robots/dor_repo/gis_delivery/load_raster_spec.rb
- spec/robots/dor_repo/gis_delivery/load_vector_spec.rb
* fix #827
* while in the code directly relevant to that ticket, do some refactoring and comment cleanup to (hopefully) make things more maintainable.  and shore up test coverage as well.
- https://argo-stage.stanford.edu/view/hj013px5098 and https://argo-stage.stanford.edu/view/bp296xj0892
- add (or at least ticket adding) an integration test that will add `gisDeliveryWF` `load-raster` coverage
- ticketed as https://github.com/sul-dlss/infrastructure-integration-test/issues/699
> LoadRaster and LoadVector: refactor to remove Dir.chdir calls, and to improve maintainability

- README.md
- bin/run_delivery
- lib/robots/dor_repo/gis_delivery/metadata_cleanup.rb
- spec/robots/dor_repo/gis_delivery/metadata_cleanup_spec.rb
Fixes #840 
Cleans up the staging path for the druid by removing the `contents` data and recursively removing parent directories until a non-empty path is found.
Unit test, verified locally that a close matching druid (i.e. `ab987th1234`) will not be removed when removing the druid tree for `ab123cd4567`.
Integration tests:
- https://argo-stage.stanford.edu/view/druid:mz464kc4897 (via preassembly)
- https://argo-stage.stanford.edu/view/druid:xn075jf4709 (non preassembly)
both show a successful `metadata-cleanup` step and I verified the druid paths are no longer on the staging directory.
> Add a step to the end of gisDeliveryWF that cleans the stage path

- lib/gis_robot_suite/raster_normalizer.rb
Since load_raster expects to be able to rsync the statistics file that
is generated during the normalization step, we should have the
normalizer raise an error if it didn't get generated.
Refs #854
unit tests
> Ensure stats file is created

- lib/gis_robot_suite/raster_normalizer.rb
- lib/robots/dor_repo/gis_delivery/load_raster.rb
- spec/gis_robot_suite/raster_normalizer_spec.rb
- spec/robots/dor_repo/gis_delivery/load_raster_spec.rb
Experimentation suggests that the `.aux.xml` file is not actually needed by Geoserver and @kimdurante suggested that we no longer need to do this.
Fixes #854
I ran a GIS item through Preassembly which gdalinfo doesn't create a .aux.xml file for. The accessioned data is in 002.zip in the Difficult Data folder: https://drive.google.com/drive/u/0/folders/1gY6_SgLWwJhtJrYsiAG5X5kgda741Lyo
@kimdurante also did some testing in stage
> No longer generate or copy `.aux.xml` statistics file.

- .rubocop_todo.yml
- lib/robots/dor_repo/gis_delivery/load_geoserver.rb
- spec/robots/dor_repo/gis_delivery/load_geoserver_spec.rb
Calling [Style.create](https://github.com/samvera-labs/geoserver-publish/blob/aec7c64311a17e2e948dd43b6523fdcc604d2837/lib/geoserver/publish/style.rb#L28-L32) without a filename causes Geoserver to throw a 500 error. This commit supplies a filename using the layer name + the ".sld" extension.
Fixes #860
Running unit tests, and running the data through Preassembly in Stage and confirming it made it through accessioning. https://argo-stage.stanford.edu/view/druid:rz417vq6403
> Send filename when creating and updating styles

- .gitignore
- spec/spec_helper.rb
match some of the rspec config we have elsewhere, for more robust unit testing (test order randomization, disallow stubbing/mocking non-existent methods, etc)
unit test only
> add RSpec setup that we use in most other apps

- lib/gis_robot_suite.rb
- lib/gis_robot_suite/arcgis_metadata_transformer.rb
- lib/gis_robot_suite/descriptive_metadata_builder.rb
- lib/gis_robot_suite/raster_normalizer.rb
- lib/gis_robot_suite/vector_normalizer.rb
- lib/robots/dor_repo/gis_assembly/extract_boundingbox.rb
- lib/robots/dor_repo/gis_assembly/generate_descriptive.rb
- lib/robots/dor_repo/gis_delivery/load_geoserver.rb
- lib/robots/dor_repo/gis_delivery/load_raster.rb
- lib/robots/dor_repo/gis_delivery/load_vector.rb
- spec/gis_robot_suite/descriptive_metadata_builder_spec.rb
- spec/gis_robot_suite/raster_normalizer_spec.rb
- spec/gis_robot_suite/vector_normalizer_spec.rb
- spec/gis_robot_suite_spec.rb
- spec/robots/dor_repo/gis_assembly/extract_boundingbox_spec.rb
- spec/robots/dor_repo/gis_assembly/generate_descriptive_spec.rb
- spec/robots/dor_repo/gis_delivery/load_geoserver_spec.rb
- spec/robots/dor_repo/gis_delivery/load_raster_spec.rb
- spec/robots/dor_repo/gis_delivery/load_vector_spec.rb
fixes #820
This PR gets rid of all of the uses i could find of `Kernel.system`, `Object#system` (i.e. just `system` from within whatever class), and `IO.popen` that I could find.  I didn't see any commands executed by wrapping a string in backticks, other than one very idiomatic (for us at least) `git` call in `config/deploy.rb`.
The PR switches them out for a new method, `GisRobotSuite.run_system_command`, which makes the error handling and error message surfacing more consistent and robust, imho.  This should hopefully make it easier to figure out why a workflow step fails when it hits an error executing a command (esp when the failure is transient, specific to the input data, or encountered on a temp file).
⚡ ⚠ If this change involves consuming from other services or writing to shared …
> Better system call error handling

- Gemfile
- Gemfile.lock
> Remove unused stanford-mods dependency

- README.md
- lib/robots/dor_repo/gis_delivery/start_accession_workflow.rb
- spec/robots/dor_repo/gis_delivery/start_accession_workflow_spec.rb
Fixes #873
This initiates the accessioning workflow and makes sure accessioning does not receive an open object version.
CI
> Change start-accessioning-workflow so it closes the object version

- lib/gis_robot_suite/raster_normalizer.rb
- spec/gis_robot_suite/raster_normalizer_spec.rb
If a filename has spaces in it, a system command that includes it as an
argument is likely to fail unless it is quoted. This is done pretty much
everywhere else in gis-robot-suite, but there were a few edge cases.
Fixes #878
* unit tests
* integration tests
> Ensure system commands quote filenames

- lib/robots/dor_repo/gis_delivery/load_vector.rb
- spec/robots/dor_repo/gis_delivery/load_vector_spec.rb
We need to retry loading with LATIN1 when the initial load as UTF-8 fails. When we changed the exception handling around GisRobotSuite::run_system_command the type of exception that was thrown also got changed which meant the fallback to load as LATIN1 failed to execute.
Fixes #883
Unit tests.
> load-vector needs to catch the correct exception

- lib/robots/dor_repo/gis_delivery/load_vector.rb
Closer inspection of the error in the log showed that the system call
was succeeding, but the exit code being non-zero triggered a different
exception: SystemCommandNonzeroExit. Catching SystemCommandError will
catch both SystemCommandNonzeroExit and SystemCommandExecutionError.
(hopefully) fixes #883
unit tests & ci
> Need to catch SystemCommandNonzeroExit too

- lib/robots/dor_repo/gis_assembly/start_gis_assembly_workflow.rb
- spec/robots/dor_repo/gis_assembly/start_gis_assembly_workflow_spec.rb
> Raise an error when starting workflow on an object that is not open

- Gemfile
- Gemfile.lock
This dependency is moving out of stdlib in Ruby 3.4 so it must be managed by bundler.
CI
> Add csv dependency to bundler

- .circleci/config.yml
- .rubocop.yml
- README.md
- lib/gis_robot_suite/gazetteer.rb
patch party to upgrade all deployed environments to ruby 3.4.1
integration tests on stage and QA (gis_accessioning_spec, preassembly_gis_raster_accessioning_spec, preassembly_gis_vector_accessioning_spec)
> Ruby 3.4.1
