- robots/gisDiscovery/generate-geoblacklight.rb
> adds the rightsMetadata datastream to the geoblacklight xml. 

- robots/gisDiscovery/export-opengeometadata.rb
> use JSON rather than XML for geoblacklight

- robots/gisAssembly/load-geo-metadata.rb
> add Dataset : GIS tag

- robots/gisAssembly/normalize-data.rb
> pass ENCODING="" to ogr2ogr to prevent recoding

- config/deploy.rb
2.2.2 is the ruby version installed on our VMs
> upgrade to ruby 2.2.2

- .travis.yml
Note 2.4.1 does not work as-is
> upgrade to ruby 2.3.4

- lib/xslt/mods2geoblacklight.xsl
This PR is connected to https://github.com/sul-dlss/earthworks/issues/341
cc: @mejackreed @kimdurante
> use github to retrieve ISO19139 data and nix HTML version

- Gemfile
- Gemfile.lock
> update RSolr to 2.x

- robots/gisDiscovery/generate-geoblacklight.rb
This PR adds the OpenIndexMaps link to dct_references. It checks contentMetadata for an `index_map.json`.
I've tested this in -dev (although `accessionWF` is broken there).
The contentMetadata looks like:
```xml
<file preserve="no" shelve="yes" publish="yes" id="index_map.json" mimetype="application/json" size="12" role="master">
<checksum type="sha1">22596363b3de40b06f981fb85d82312e8c0ed511</checksum>
<checksum type="md5">6f5902ac237024bdd0c176cb93063dc4</checksum>
</file>
```
and the dct_references look like:
```
"dct_references_s": "{\"http://schema.org/url\":\"http://purl.stanford.edu/gk100kn3697\",\"http://schema.org/downloadUrl\":\"http://stacks-dev.stanford.edu/file/druid:gk100kn3697/data.zip\",\"http://www.loc.gov/mods/v3\":\"http://purl.stanford.edu/gk100kn3697.mods\",\"http://www …
```
> adds an OpenIndexMaps pointer to stacks if we are dealing with an index map

- lib/gis-robot-suite/utils.rb
> add UInt16 as a supported type

- config/boot.rb
> require honeybadger for exception logging

- robots/gisDelivery/load-geoserver.rb
These links are no longer used in the GeoServer catalog.
cc @mejackreed
> remove unused metadata links in GeoServer catalog

- robots/gisDelivery/load-geoserver.rb
https://github.com/sul-dlss/rgeoserver/blob/b161829cc198167300d7ae7d17d945d5cabe6f86/lib/rgeoserver/featuretype.rb#L111
Closes #141 
cc @ndushay
> provide an empty metadata array for rgeoserver

- Gemfile
- Gemfile.lock
> Reverted to activemodel 5.1.7.

- config/environments/example.rb
- config/settings.yml
- robots/gisDiscovery/generate-geoblacklight.rb
> Add settings for stacks url

- .travis.yml
- Gemfile
- Gemfile.lock
add 2.7.1 to travis
n/a
If so, please confirm change was tested on stage and/or test added to sul-dlss/infrastructure-integration-test.
n/a
> add 2.7.1 to travis; update bundler

- robots/gisAssembly/generate-content-metadata.rb
Existing documentation was incorrect
n/a
n/a
> Correct YARD documentation around content metadata

- .gitignore
- config/environments/production.rb
- config/environments/staging.rb
Depends on https://github.com/sul-dlss/shared_configs/pull/1407 and https://github.com/sul-dlss/shared_configs/pull/1406
The prepares us to move to dor-services-app 9 and is consistent with
our other robot suites.
test suite
n/a
> Check-in the prod and staging environment configs

- config/deploy.rb
- config/environments/production.rb
- config/environments/staging.rb
Depends on https://github.com/sul-dlss/shared_configs/pull/1409
☝️ 
Can't be tested without deploying. 😢 
config/deploy.rb
> We now use the environment file that is checked into the repo

- .rubocop.yml
- Gemfile
- Gemfile.lock
- lib/robots/dor_repo/gis_assembly/load_geo_metadata.rb
- spec/unit/gisAssembly/load_geo_metadata_spec.rb
Decoupling from Fedora 3.  Ref #296 
Test suite
n/a
> Update geoMetadata using the dor-services-app legacy metadata endpoint

- Gemfile
- Gemfile.lock
- spec/robots/dor_repo/gis_delivery/load_geoserver_spec.rb
Upgrade gems.  merge AFTER #314 (will need a rebase first)
test suite
Gemfile
> Upgrade rake

- config/environments/production.rb
- config/environments/staging.rb
- lib/gis_robot_suite.rb
- lib/robots/dor_repo/gis_assembly/assign_placenames.rb
- lib/robots/dor_repo/gis_assembly/author_metadata.rb
- lib/robots/dor_repo/gis_assembly/extract_boundingbox.rb
- lib/robots/dor_repo/gis_assembly/extract_iso19139.rb
- lib/robots/dor_repo/gis_assembly/extract_thumbnail.rb
- lib/robots/dor_repo/gis_assembly/finish_data.rb
- lib/robots/dor_repo/gis_assembly/finish_gis_assembly_workflow.rb
- lib/robots/dor_repo/gis_assembly/finish_metadata.rb
- lib/robots/dor_repo/gis_assembly/generate_content_metadata.rb
- lib/robots/dor_repo/gis_assembly/generate_geo_metadata.rb
- lib/robots/dor_repo/gis_assembly/generate_mods.rb
- lib/robots/dor_repo/gis_assembly/load_geo_metadata.rb
- lib/robots/dor_repo/gis_assembly/normalize_data.rb
- lib/robots/dor_repo/gis_assembly/package_data.rb
- lib/robots/dor_repo/gis_assembly/start_assembly_workflow.rb
- lib/robots/dor_repo/gis_assembly/start_delivery_workflow.rb
- lib/robots/dor_repo/gis_assembly/wrangle_data.rb
- lib/robots/dor_repo/gis_delivery/finish_gis_delivery_workflow.rb
- lib/robots/dor_repo/gis_delivery/load_geoserver.rb
- lib/robots/dor_repo/gis_delivery/load_raster.rb
- lib/robots/dor_repo/gis_delivery/load_vector.rb
- lib/robots/dor_repo/gis_delivery/start_gis_discovery_workflow.rb
- lib/robots/dor_repo/gis_discovery/export_opengeometadata.rb
- lib/robots/dor_repo/gis_discovery/generate_geoblacklight.rb
- lib/robots/dor_repo/gis_discovery/load_geoblacklight.rb
This option was never used and was unnecessary.
Test suite
n/a
> Remove the ROBOT_DELAY, which was never used

- README.md
> Be more explicit in README about the needed dependencies

- lib/robots/dor_repo/gis_delivery/load_geoserver.rb
- spec/robots/dor_repo/gis_delivery/load_geoserver_spec.rb
Suggested https://github.com/sul-dlss/gis-robot-suite/pull/333#discussion_r451610193 by @jcoyne but needed to fixup the test.
Using a test.
n/a
> Use dor-services method for determining rights

- lib/robots/dor_repo/gis_assembly/generate_content_metadata.rb
Fixes #345 
Logged into production and tested if call is correct. 
n/a
> Updates gem call with correct prefix

- README.md
- config/deploy.rb
Rename default branch to `main`
Testing suite
README and deploy.rb
> Rename master to main

- Gemfile.lock
> Update cocina-models to 0.61.1

- Gemfile.lock
> Update to use activesupport 7

- Gemfile
- Gemfile.lock
> Upgrade to the latest version of the config gem

- .circleci/config.yml
- .rubocop.yml
- Gemfile
- Gemfile.lock
- spec/unit/utils_spec.rb
> Test on Ruby 3

- Gemfile
- Gemfile.lock
> Unpin and bump dlss-capistrano to 4.0.0

- lib/robots/dor_repo/gis_assembly/normalize_data.rb
Ref #466
Tested by Kim in prod.
> Use URI.open rather than Kernel#open.

- .rubocop.yml
- lib/robots/dor_repo/gis_delivery/load_vector.rb
The machine has got me!  Help!
> appease rubocop masters

- lib/robots/dor_repo/gis_assembly/generate_content_metadata.rb
We always overwrite these values, so we don't need to set them in the first place
CI
> Remove the file defaults hash

- .circleci/config.yml
>  bump sul-dlss circleci orb to 3.1.2

- Gemfile
- Gemfile.lock
Unnecessary lines of code, or dependencies, make maintenance harder than it should be.
I ran [Peter's handy new gis robots integration test](https://github.com/sul-dlss/infrastructure-integration-test/pull/468)
Also, unit tests run cleanly.
> Gemfile: remove unnecessary gems and reorg

- README.md
> README cleanup.

- .circleci/config.yml
- .rubocop.yml
- Gemfile.lock
- lib/gis_robot_suite/gazetteer.rb
- lib/robots/dor_repo/gis_assembly/generate_content_metadata.rb
- lib/robots/dor_repo/gis_assembly/generate_mods.rb
- lib/robots/dor_repo/gis_delivery/load_geoserver.rb
Keep pace with Ruby releases.
CI and will integration-tested in stage
> Upgrade to Ruby 3.2.2

- Gemfile.lock
See https://github.com/sul-dlss/assembly-objectfile/pull/141
CI and will be tested in deployed envs
> Bump assembly-objectfile to pick up a prod bugfix

- README.md
also, opportunistic wording cleanup.
fix https://github.com/sul-dlss/argo/issues/4057
> add a section to the README explaining how to reset the app in stage and/or QA

- Gemfile
- Gemfile.lock
> Bump DSC to version 13

- Gemfile
- Gemfile.lock
> Remove rsolr

- lib/robots/dor_repo/gis_assembly/normalize_data.rb
> Refactor variable names in Normalize Data robot.

- .rubocop.yml
- lib/gis_robot_suite.rb
- lib/robots/dor_repo/gis_assembly/normalize_data.rb
- lib/robots/dor_repo/gis_delivery/load_geoserver.rb
- lib/robots/dor_repo/gis_delivery/load_vector.rb
- spec/robots/dor_repo/gis_delivery/load_geoserver_spec.rb
- spec/unit/utils_spec.rb
Remove dependency on MODS.
Unit
> Refactor determine file format

- lib/robots/dor_repo/gis_assembly/assign_placenames.rb
- spec/robots/dor_repo/gis_assembly/assign_placenames_spec.rb
> Refactors Assign Placenames robot to use cocina.

- spec/unit/utils_spec.rb
> Fix utils spec so that it doesn't flap.

- lib/robots/dor_repo/gis_delivery/load_geoserver.rb
- spec/robots/dor_repo/gis_delivery/load_geoserver_spec.rb
To allow descMetadata.xml to be removed.
> Refactor load geoserver

- README.md
Add links for general information about the GIS domain, as well as motivations for adding support to the SDR.
> Links for GIS information

- .rubocop.yml
> Update rubocop rules

- lib/robots/dor_repo/gis_assembly/normalize_data.rb
So that the code can be understood.
> Refactor norm robot

- Gemfile.lock
- lib/robots/dor_repo/gis_delivery/load_geoserver.rb
Cleaner to use Cocina directly.
Unit
> Removes use of MODS from Load Geoserver robot

- lib/robots/dor_repo/gis_assembly/extract_boundingbox.rb
- spec/robots/dor_repo/gis_assembly/extract_boundingbox_spec.rb
> Refactors Extract Boundingbox robot to use cocina directly.

- spec/robots/dor_repo/gis_assembly/generate_content_metadata_spec.rb
small follow on to #727 to exercise what i think was a previously uncovered codepath.  this doesn't increase the number of lines covered, but it does exercise the case where `if access[:view] == 'citation-only'` evaluates to true in this code (i.e. the case where the parent object has `citation-only` view rights): https://github.com/sul-dlss/gis-robot-suite/blob/df83448776b82c2405b3563c7c86660b4c5a26bb/lib/robots/dor_repo/gis_assembly/generate_content_metadata.rb#L71-L77
unit test only change
> add test of citation-only view rights on parent object when creating structural metadata for GIS files

- lib/robots/dor_repo/gis_assembly/package_data.rb
to reduce cognitive load when reading the code.  Please review carefully.
CI
> package_data: less cryptic var names

- spec/gis_robot_suite_spec.rb
closes #751 
Follow rspec conventions to lower cognitive load.
CI
> move gis_robot_suite specs to expected location

- bin/run_delivery
- lib/robots/dor_repo/gis_delivery/reload_geoserver.rb
> Reload-geoserver robot step

- README.md
> Add missed update to README in reload server PR

- lib/robots/dor_repo/gis_assembly/extract_iso19110_metadata.rb
- lib/robots/dor_repo/gis_assembly/package_data.rb
- spec/robots/dor_repo/gis_assembly/extract_iso19110_metadata_spec.rb
noticed a few possibly beneficial tweaks when reviewing #778
existing unit tests
> Accession geojson  nitpicks

- lib/gis_robot_suite/raster_normalizer.rb
- lib/robots/dor_repo/gis_assembly/extract_boundingbox.rb
- spec/gis_robot_suite/raster_normalizer_spec.rb
since it's not producing the desired results as currently implemented
fixes #823
> stop adding alpha channel to GeoTIFFs

- lib/robots/dor_repo/gis_assembly/finish_gis_assembly_workflow.rb
- spec/fixtures/stage/bb045mm1234/content/somefile.shp
- spec/fixtures/stage/bb045mm1234/content/somefile.txt
- spec/robots/dor_repo/gis_assembly/finish_gis_assembly_workflow_spec.rb
- spec/robots/dor_repo/gis_assembly/generate_tag_spec.rb
- spec/robots/dor_repo/gis_delivery/finish_gis_delivery_workflow_spec.rb
- spec/robots/dor_repo/gis_delivery/load_geoserver_spec.rb
- spec/robots/dor_repo/gis_delivery/reset_geowebcache_spec.rb
- spec/spec_helper.rb
Fixes #756 - add a new spec for FinishGisAssembly robot
CI
> [HOLD] Add new test for FinishGisAssembly Robot

- lib/robots/dor_repo/gis_delivery/load_geoserver.rb
- spec/robots/dor_repo/gis_delivery/load_geoserver_spec.rb
~~WIP - adjust expectations a bit~~
Fixes #763 - additional test coverage for LoadGeoserver.
CI
> Add additional test cover for LoadGeoserver

- lib/robots/dor_repo/gis_delivery/load_raster.rb
- spec/robots/dor_repo/gis_delivery/load_raster_spec.rb
Related to #854 ... does not actually fix this bug, and the current code works for this particular line, but I think this might be clearer
Updated spec, on stage
> move location of close apostraphe to make code clearer

- spec/spec_helper.rb
caught oversights from prior rspec config improvement when looking at similar https://github.com/sul-dlss/was_robot_suite/pull/678 (follow on from #867)
spec only
> more rspec configuration improvement

- lib/robots/dor_repo/gis_assembly/start_gis_assembly_workflow.rb
- spec/robots/dor_repo/gis_assembly/start_gis_assembly_workflow_spec.rb
Connects to sul-dlss/workflow-server-rails#750
CI
> Add robot to start GIS assembly workflow

- Gemfile
- Gemfile.lock
Update sidekiq to latest.
Stage
> Update lyber-core and sidekiq
